@startuml "aws_group_icons"

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v11.1/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/AWSSimplified.puml

!include AWSPuml/GroupIcons/Cloud.puml
!include AWSPuml/GroupIcons/VirtualPrivateCloudVPC.puml
!include AWSPuml/GroupIcons/VPCSubnetPrivate.puml
!include AWSPuml/GroupIcons/VPCSubnetPublic.puml

skinparam PackageTitleAlignment Left

!unquoted procedure AWSGroupColoring($g_stereo, $g_background_color, $g_border_color, $g_border_style)
  skinparam rectangle<<$g_stereo>> {
    backgroundColor $g_background_color
    borderColor $g_border_color
    borderStyle $g_border_style
    shadowing false
  }
!endprocedure

!unquoted function $getSprite($g_sprite)
  !if %strlen($g_sprite) == 0
    !return ''
  !else
    !return "<$" + $g_sprite + "{scale=.5}> "
  !endif
!endfunction

!unquoted procedure AWSGroupEntity($g_alias, $g_label, $g_color, $g_sprite, $g_stereo)
rectangle "<color:$g_color>$getSprite($g_sprite)$g_label</color>" as $g_alias <<$g_stereo>>
!endprocedure

AWSGroupColoring(Cloud, #FFFFFF, #232F3E, plain)
!unquoted procedure CloudGroup(g_alias, g_label)
AWSGroupEntity(g_alias, g_label, #232F3E, Cloud, Cloud)
!endprocedure

AWSGroupColoring(VirtualPrivateCloudVPC, #FFFFFF, #3F8624, plain)
!unquoted procedure VirtualPrivateCloudVPCGroup(g_alias, g_label)
AWSGroupEntity(g_alias, g_label, #3F8624, VirtualPrivateCloudVPC, VirtualPrivateCloudVPC)
!endprocedure

AWSGroupColoring(VPCSubnetPrivate, #E6F2E7, Transparent, plain)
!unquoted procedure VPCSubnetPrivateGroup(g_alias, g_label)
AWSGroupEntity(g_alias, g_label, #3F8624, VPCSubnetPrivate, VPCSubnetPrivate)
!endprocedure

AWSGroupColoring(VPCSubnetPublic, #E7F2F8, Transparent, plain)
!unquoted procedure VPCSubnetPublicGroup(g_alias, g_label)
AWSGroupEntity(g_alias, g_label, #3B48CC, VPCSubnetPublic, VPCSubnetPublic)
!endprocedure

AWSGroupColoring(AvalabilityZone, #FFFFFF, #03A0C7, dashed)
!unquoted procedure AvalabilityZoneGroup(g_alias, g_label)
AWSGroupEntity(g_alias, g_label, #03A0C7, "", AvalabilityZone)
!endprocedure

AWSGroupColoring(ManagedServices, #FFFFFF, #232F3E, dashed)
!unquoted procedure ManagedServicesGroup(g_alias, g_label)
AWSGroupEntity(g_alias, g_label, #232F3E, "", ManagedServices)
!endprocedure

@enduml
