@startuml "hidden_join"

skinparam interface<<invisible>> {
  shadowing false
  backgroundColor transparent
  borderColor transparent
}

skinparam rectangle<<invisible>> {
  shadowing false
  BackgroundColor transparent
  BorderColor transparent
}

!unquoted procedure HiddenJoin($p_alias)
() "<color:transparent>a</color>" as $p_alias<<invisible>>
!endprocedure

!unquoted procedure HiddenRectangle($p_alias)
rectangle "<color:transparent>a</color>" as $p_alias <<invisible>>
!endprocedure

@enduml
